"""initial_tables_users_audit_events_sensitive_rules

Revision ID: d73d9e05e6c7
Revises: 
Create Date: 2026-06-10 02:03:10.877130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd73d9e05e6c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensitive_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('action_pattern', sa.String(length=200), nullable=True),
    sa.Column('resource_type_pattern', sa.String(length=200), nullable=True),
    sa.Column('resource_id_pattern', sa.String(length=200), nullable=True),
    sa.Column('actor_pattern', sa.String(length=200), nullable=True),
    sa.Column('min_severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'), nullable=True),
    sa.Column('alert_enabled', sa.Boolean(), nullable=True),
    sa.Column('alert_channels', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensitive_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensitive_rules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensitive_rules_is_active'), ['is_active'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('actor_name', sa.String(length=200), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=True),
    sa.Column('actor_ip', sa.String(length=45), nullable=True),
    sa.Column('actor_user_agent', sa.String(length=500), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'EXPORT', 'IMPORT', 'APPROVE', 'REJECT', 'OTHER', name='eventaction'), nullable=False),
    sa.Column('action_detail', sa.String(length=500), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('resource_name', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILURE', 'PENDING', 'BLOCKED', name='eventstatus'), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel'), nullable=True),
    sa.Column('matched_rule_id', sa.Integer(), nullable=True),
    sa.Column('service_name', sa.String(length=100), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['matched_rule_id'], ['sensitive_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index('idx_action_timestamp', ['action', 'timestamp'], unique=False)
        batch_op.create_index('idx_actor_timestamp', ['actor_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_resource_timestamp', ['resource_type', 'resource_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_sensitive_severity', ['is_sensitive', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_name'), ['actor_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_event_id'), ['event_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_audit_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_is_sensitive'), ['is_sensitive'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_service_name'), ['service_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_events_status'))
        batch_op.drop_index(batch_op.f('ix_audit_events_severity'))
        batch_op.drop_index(batch_op.f('ix_audit_events_service_name'))
        batch_op.drop_index(batch_op.f('ix_audit_events_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_events_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_is_sensitive'))
        batch_op.drop_index(batch_op.f('ix_audit_events_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_name'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))
        batch_op.drop_index('idx_sensitive_severity')
        batch_op.drop_index('idx_resource_timestamp')
        batch_op.drop_index('idx_actor_timestamp')
        batch_op.drop_index('idx_action_timestamp')

    op.drop_table('audit_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('sensitive_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensitive_rules_is_active'))
        batch_op.drop_index(batch_op.f('ix_sensitive_rules_id'))

    op.drop_table('sensitive_rules')
    # ### end Alembic commands ###
